### ISSUE TITLE
gamerjay@live.ca

### ISSUE THREAD

**Issue by gamerjay** [PeterLemon/N64#1]

**Comment by theboy181** [comment]
???

**Comment by gamerjay** [comment]
whens translatio gonna be done of sim city 64

**Comment by PeterLemon** [comment]
Hi gamerjay, I do not know when it will be finished, I am the only person working on this translation at the moment, so progress is slow, sorry about that.

**Comment by Kerr-Avon-2015** [comment]
Peter,

I just wanted to say thank you for the hard work you are putting into this. As an N64 fan back during the N64 years (and through to today, it's still my favourite console), the only 64DD game I wanted was SimCity 64, as it looked amazing, with it's 3D street view, and vehicle based views. Realistically, I doubted I'd be able to buy a 64DD system, and I never did, but I always hoped that the game would be re-released in cartridge form, but of course it never did. A real pity, all the more so since us N64 fans often had to wait for the next (good) release from time to time, and SimCity 64 would have been a brilliant addition to the stock system's library.

But now that the Everdrive 64 can play the 64DD games, I finally can play SimCity 64, and so I am really looking forward to seeing a finished translation of the game. I know you're probably very busy, so it might be a while before the translation is done, but it will be worth waiting for, as being able to play this unique version of SimCity 2000 will be brilliant!

So please don't abandon this project, or think that no one would be interest in it. I'm sure Gamerjay (above) and I aren't the only ones eagerly awaiting the finished product. And Happy Christmas and New Year, by the way, to you and anyone else reading this.

**Comment by Kerr-Avon-2015** [comment]
Peter,

I've just e-mailed you with this, but in case the e-mail address I found is too old, or
no longer used by you, I thought I'd post here, I hope you don't mind.

Sorry to bother you, but I am having trouble applying your SimCity64 patch,
and I was hoping you could detail the correct method for me. I've correctly patched
dozens of N64 files, with many formats of patches, including .xdelta, but I can't
get this one to work. It's probably just me being stupid, but no matter what version
of the Xdelta patcher I download and use, when I try to apply the patch (to a clean rom,
of course), I just get an error message saying:


xdelta3: not a VCDIFF input: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent


I don't know how to verify the file how it says, but I've re-downloaded the SimCity64 unpatched rom v1.1  from:

https://64dd.org/dumps_p.html

in case it was somehow corrupted when I first downloaded it (although surely that would have given me a ZIP related error when I unzip the rom?), but it gives the same result. So please can you tell me  which version of what Xdelta patcher I should use (and where to download it), and what command line arguments to use to get it to work.

Thanks for all your trouble, mate, and for your great work with SimCity64 (the only 64DD game I'm really interested in, I really wish it had been released on cartridge!).

**Comment by PeterLemon** [comment]
Hi Kerr-Avon-2015,

I use the windows 64-bit 3.0.11 stable version of Xdelta 3 from here: http://xdelta.org/

I rename the executable to xdelta3.exe, & use this command to apply the patch:
xdelta3 -d -s NUD-DSCJ-JPN.n64 NUD-DSCJ-JPN.n64.xdelta3 SimCity-64.n64

Also I have added 2 new "applycartpatch.bat" "applydiskpatch.bat" files to help make this easier.

Hope this helps =D

**Comment by Kerr-Avon-2015** [comment]
Hello mate,

Thanks for replying! And after following your advice and failing, I've
finally located the problem!

User stupidity. Yes, unfortunately it was me cocking it up. I don't think
I've ever downloaded
anything from github before, and so, when downloading
the NUD-DSCJ-JPN.n64.xdelta3 file,
I just right clicked and chose SAVE AS, which meant I was downloading a web
page (44k)
instead of the patch (9k). I didn't realise until I downloaded and tried to
run the file
applycartpatch.bat and it failed to run, and when I viewed it's contents I
realised that I'd
downloaded a web page and not a batch file.

Anyway, I put both of my brain cells to work, properly downloaded
NUD-DSCJ-JPN.n64.xdelta3,
and the patching process worked perfectly. So thanks for the detailed
advice, and my apologies for
bothering you when the problem was just me making a very basic mistake.




BTW, someone called Ozidual is also working on a translation of SimCity 64.
He's the same bloke
(or lady, I dunno) who has made the Gamecube versions of Ocarina of Time
run on the N64, with
various changes and touch-ups:

http://krikzz.com/forum/index.php?topic=5281.0

and the fantastic bug fixes for Space Station: Silicon Valley:

http://krikzz.com/forum/index.php?topic=6946.0

he mentions it here:

http://krikzz.com/forum/index.php?topic=6982.0

Maybe you and he can help one-another with the SC 64 translation, I know
he's friendly and helpful.
And it was thanks to his post there that I found your new patch.


Cheers mate, and thanks again,

Carl.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
